// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestEFPowerTool.Models;

[Table("Appointment")]
public partial class Appointment
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("appointment_type")]
    public int AppointmentType { get; set; }

    [Column("number")]
    public int Number { get; set; }

    [Column("date")]
    public DateOnly Date { get; set; }

    [Column("slot_id")]
    public int SlotId { get; set; }

    [Column("customer_id")]
    public int CustomerId { get; set; }

    [Column("dentist_id")]
    public int DentistId { get; set; }

    [Column("cycle_count")]
    public int CycleCount { get; set; }

    [Required]
    [Column("dentist_note")]
    [StringLength(1000)]
    public string DentistNote { get; set; }

    [Column("appointment_status")]
    public int AppointmentStatus { get; set; }

    [Column("price_final")]
    public int PriceFinal { get; set; }

    [InverseProperty("Appointment")]
    public virtual ICollection<BookedService> BookedServices { get; set; } = new List<BookedService>();

    [ForeignKey("CustomerId")]
    [InverseProperty("AppointmentCustomers")]
    public virtual Account Customer { get; set; }

    [ForeignKey("DentistId")]
    [InverseProperty("AppointmentDentists")]
    public virtual Account Dentist { get; set; }

    [ForeignKey("SlotId")]
    [InverseProperty("Appointments")]
    public virtual ClinicSlot Slot { get; set; }
}