// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestEFPowerTool.Models;

[Table("Clinic")]
public partial class Clinic
{
    [Key]
    [Column("clinic_id")]
    public int ClinicId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(128)]
    public string Name { get; set; }

    [Required]
    [Column("address")]
    [StringLength(128)]
    public string Address { get; set; }

    [Required]
    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Required]
    [Column("phone")]
    [StringLength(10)]
    public string Phone { get; set; }

    [Required]
    [Column("email")]
    [StringLength(64)]
    public string Email { get; set; }

    [Column("open_hour")]
    public TimeOnly OpenHour { get; set; }

    [Column("close_hour")]
    public TimeOnly CloseHour { get; set; }

    [Column("working")]
    public bool Working { get; set; }

    [Column("clinic_status")]
    public int ClinicStatus { get; set; }
}