// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestEFPowerTool.Models;

[Table("ServiceCategory")]
public partial class ServiceCategory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(32)]
    public string Name { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<ClinicService> ClinicServices { get; set; } = new List<ClinicService>();
}